[package]
name = "lushui_documenter"
version = "0.0.0"
description = "The documentation generator for Lushui projects"
edition = "2021"
publish = false

[dependencies]
crossbeam = "0.8.1"
html-escape = "0.2.9"
joinery = "2.1.0"
lushui_ast = { path = "../ast" }
lushui_entity = { path = "../entity" }
lushui_error = { path = "../error" }
lushui_hir = { path = "../hir" }
lushui_lowered_ast = { path = "../lowered_ast" }
lushui_resolver = { path = "../resolver" }
lushui_session = { path = "../session" }
lushui_syntax = { path = "../syntax" }
lushui_utilities = { path = "../utilities" }
minifier = "0.2.1"
unicode-segmentation = "1.9.0"
urlencoding = "2.1.0"
