[package]
name = "documenter"
version = "0.0.0"
description = "The documentation generator"
edition = "2021"
publish = false

[dependencies]
crossbeam = "0.8.1"
derivation = { path = "../../project/library/derivation" }
error = { path = "../error" }
hir = { path = "../hir" }
hir_format = { path = "../hir_format" }
html-escape = "0.2.9"
joinery = "3.1.0"
minifier = "0.2.1"
resolver = { path = "../resolver" }
session = { path = "../session" }
syntax = { path = "../syntax" }
token = { path = "../token" }
unicode-segmentation = "1.9.0"
urlencoding = "2.1.0"
utilities = { path = "../utilities" }
