cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "compiler/*",
    "project/library/*",
    "library/core/source/boot",
    "test/ui/framework",
]
default-members = ["compiler/main"]
resolver = "2"
