[package]
name = "lushui"
version = "0.1.0"
description = "The reference compiler of the Lushui programming language"
authors = ["León Orell Valerian Liehr <liehr.exchange@gmx.net>"]
edition = "2018"
publish = false

[dependencies]
colored = "2.0.0"
string_cache = { version = "0.8.0", default-features = false }
num-bigint = "0.3.0"
num-traits = "0.2.11"
smallvec = { version = "1.4.2", features = ["const_generics"] } 
bitflags = "1.2.1"
clap = "2.33.3"
indexed_vec = { version = "1.2.1", default-features = false }
unicode-width = "0.1.7"
once_cell = "1.3.1"
joinery = "2.0.0"
strsim = "0.10.0"
rustc-hash = "1.1.0"
difference = "2.0.0"
serde = { version =  "1.0.126", features = ["derive"] }
json5 = "0.3.0"
