[package]
name = "lushui"
version = "0.1.0"
description = "The reference compiler of the Lushui programming language"
authors = ["León Orell Valerian Liehr <liehr.exchange@gmx.net>"]
edition = "2018"
publish = false

[dependencies]
colored = "1.9.1"
string_cache = "0.8.0"
num-bigint = "0.2.5"
num-traits = "0.2.11"
# freestanding = { git = "https://github.com/fmease/freestanding.git", tag = "v0.1.0" }
freestanding = { path = "/home/fmease/programming/side_projects/freestanding" }
smallvec = "1.2.0"
bitflags = "1.2.1"
structopt = "0.3.14"
indexed_vec = "1.2.1"
unicode-width = "0.1.7"
once_cell = "1.3.1"
