[package]
name = "lushuic"
version = "0.1.0"
authors = ["León Orell Valerian Liehr <liehr.exchange@gmx.net>"]
edition = "2018"

[dependencies]
colored = "1.9.1"
string_cache = "0.8.0"
num-bigint = "0.2.5"
freestanding = { path = "src/freestanding" }
