= The Lushui Programming Language
:toc: left
:nofooter:

露水 lùshui :: *dew*; ephemeral, transient, of short duration

The reference compiler of the https://lushui.ml/[Lushui programming language].
Its code is hosted on https://github.com/fmease/lushui.git[GitHub]
and mirrored on https://gitlab.com/fmease/lushui.git[GitLab].

// @Task somewhere mention Cargo feature flags and workspace-related things
//       like using `--workspace` for `cargo test` etc, how to use `cargo doc`

== Stability

This project is under heavy development and
it is not recommended for use outside of experimental non-production software.
The language, the compiler API and its CLI have no stability guarantees whatsoever.
Anything may change in a new version without notice.
The majority of the language has not been implemented yet in the compiler,
the latter contains quite a lot of bugs and
the test suites are not big enough yet.

== Installation

The compiler is mainly written in https://www.rust-lang.org/[Rust] and
it uses Rust's official package manager https://doc.rust-lang.org/cargo/[Cargo].
We require the (latest) _nightly_ version of the Rust compiler `rustc`.
With https://github.com/rust-lang/rustup/[`rustup`], just execute `rustup install nightly`.

To build the Lushui compiler, run:

[source,sh]
----
cargo +nightly build
----

To show the help text on Linux, execute:

[source,sh]
----
./lushui -h
----

[subs=-replacements]
On Windows, use `cargo +nightly run -- -h`.

Currently, the shell script `./lushui` also rebuilds the compiler if necessary
(no status info shown though during building) and
runs it afterwards.

== Tests

Run the following command (Linux only) to run all test suites:

[source,sh]
----
./test/run
----

If you want to restrict yourself to UI tests, execute `./test/ui/run`.

== Tooling

=== Visual Studio Code

Basic language support (syntax highlighting and a rudimentary language server) is available as an extension.
For package metadata files, we currently provide a separate extension.
It's planned to be integrated into the main extension at some point.

==== Installation (Linux)

To build the language server, change into `./project/editors/vscode/fmease.lushui-0.0.1/` and type:

[source,sh]
----
npm install
npm run compile
----

Then, copy or symlink the folder to `~/.vscode/extensions/`.
The compiler currently needs to be built with feature `lsp` and added to the `$PATH` as `lushui-nightly`
for the language server to work.

For Lushui Metadata support, copy or symlink the folder `./project/editor/vscode/fmease.lushui-metadata-syntax-0.0.1`
to `~/.vscode/extensions/`.

== Generated API Documentation

As hinted in the help text (`./lushui -h`), you use `./lushui doc` (and variations) to generate (HTML) documentation.
To view it, just pass `--open`.

By default, documentation comments are treated as plain text.
However, the goal is to make AsciiDoc the standard markup language.
Today, this is only opt-in via the _unstable_ option `-Z asciidoc` which requires https://asciidoctor.org/[Asciidoctor]
to be installed and
available as `asciidoctor` (a custom installation path is not supported at the moment).

== License

None yet.
