#!/usr/bin/env sh

# Run unit tests (via the rust testing framework)
cargo test --quiet --manifest-path="$(dirname $(realpath $0))/Cargo.toml" -- --format pretty

# Run UI tests (via the golden UI testing framework)
./tests/ui/run
