[package]
name = "lexer"
version = "0.0.0"
description = "The lexical analyzer (lexer)"
edition = "2021"
publish = false

[dependencies]
derivation = { path = "../../project/library/derivation" }
span = { path = "../span" }
utilities = { path = "../utilities" }
