[package]
name = "syntax"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ast = { path = "../ast" }
error = { path = "../error" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
session = { path = "../session" }
span = { path = "../span" }
