[package]
name = "lushui_driver"
version = "0.0.0"
# @Task description
edition = "2021"
publish = false

[features]
llvm = ["dep:lushui_llvm_codegen"]
cranelift = ["dep:lushui_cranelift_codegen"]
lsp = ["dep:lushui_server", "dep:tokio"]

[dependencies]
clap = "3.1.5"
colored = "2.0.0"
derivation = { path = "../../project/libraries/derivation" }
lushui_cranelift_codegen = { path = "../cranelift_codegen", optional = true }
lushui_diagnostics = { path = "../diagnostics" }
lushui_documenter = { path = "../documenter" }
lushui_error = { path = "../error" }
lushui_hir = { path = "../hir" }
lushui_lexer = { path = "../lexer" }
lushui_llvm_codegen = { path = "../llvm_codegen", optional = true }
lushui_lowerer = { path = "../lowerer" }
lushui_metadata = { path = "../metadata" }
lushui_package = { path = "../package" }
lushui_parser = { path = "../parser" }
lushui_resolver = { path = "../resolver" }
lushui_server = { path = "../server", optional = true }
lushui_session = { path = "../session" }
lushui_span = { path = "../span" }
lushui_token = { path = "../token" }
lushui_typer = { path = "../typer" }
lushui_utilities = { path = "../utilities" }
open = "3.0.1"

[dependencies.tokio]
version = "1.19.2"
features = ["io-std", "rt-multi-thread"]
optional = true
