[package]
name = "token"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
derivation = { path = "../../project/library/derivation" }
diagnostics = { path = "../diagnostics" }
span = { path = "../span" }
utilities = { path = "../utilities" }
