[package]
name = "lushui_error"
version = "0.0.0"
description = "Error handling mechanisms"
edition = "2021"
publish = false

[dependencies]
lushui_diagnostics = { path = "../diagnostics" }
lushui_utilities = { path = "../utilities" }
