[package]
name = "lushui_session"
version = "0.0.0"
# @Task description
edition = "2021"
publish = false

[dependencies]
# lushui_package = { path = "../package" }
colored = "2.0.0"
derivation = { path = "../../project/libraries/derivation" }
index_map = { path = "../../project/libraries/index_map" }
lushui_ast = { path = "../ast" }
lushui_component_index = { path = "../component_index" }
lushui_diagnostics = { path = "../diagnostics" }
lushui_entity = { path = "../entity" }
lushui_error = { path = "../error" }
lushui_hir = { path = "../hir" }
lushui_span = { path = "../span" }
lushui_token = { path = "../token" }
lushui_utilities = { path = "../utilities" }
