[package]
name = "session"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
derivation = { path = "../../project/library/derivation" }
index_map = { path = "../../project/library/index_map" }
ast = { path = "../ast" }
diagnostics = { path = "../diagnostics" }
error = { path = "../error" }
hir = { path = "../hir" }
lexer = { path = "../lexer" }
span = { path = "../span" }
token = { path = "../token" }
utilities = { path = "../utilities" }
