[package]
name = "ui_test_framework"
version = "0.1.0"
description = "A golden UI testing framework for the Lushui compiler"
edition = "2024"
publish = false

[dependencies]
clap.workspace = true
derivation = { path = "../../library/derivation" }
diagnostics = { path = "../../../compiler/diagnostics" }
joinery.workspace = true
lexer = { path = "../../../compiler/lexer" }
pathdiff = "0.2.1"
recnot = { path = "../../library/recnot" }
span = { path = "../../../compiler/span" }
terminal_size = "0.4.2"
unicode-width.workspace = true
utility = { path = "../../../compiler/utility" }
walkdir = "2.5.0"
