[package]
name = "span"
version = "0.0.0"
edition = "2024"
publish = false

[features]
lsp = []
test = []

[dependencies]
index_map = { path = "../../project/library/index_map" }
unicode-width.workspace = true
utility = { path = "../utility" }
