[package]
name = "span"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
index_map = { path = "../../project/library/index_map" }
unicode-width = "0.1.10"
utilities = { path = "../utilities" }
