[package]
name = "diagnostics"
version = "0.0.0"
description = "The diagnostic system"
edition = "2024"
publish = false

[dependencies]
derivation = { path = "../../project/library/derivation" }
span = { path = "../span" }
utility = { path = "../utility" }
