[package]
name = "lushui_typer"
version = "0.0.0"
# @Task description
edition = "2021"
publish = false

[dependencies]
joinery = "2.1.0"
lushui_ast = { path = "../ast" }
lushui_diagnostics = { path = "../diagnostics" }
lushui_entity = { path = "../entity" }
lushui_error = { path = "../error" }
lushui_hir = { path = "../hir" }
lushui_lowered_ast = { path = "../lowered_ast" }
lushui_resolver = { path = "../resolver" }
lushui_session = { path = "../session" }
lushui_utilities = { path = "../utilities" }
