[package]
name = "ast"
version = "0.0.0"
description = "The Lushui abstract syntax tree (AST)"
edition = "2021"
publish = false

[dependencies]
diagnostics = { path = "../diagnostics" }
joinery = "3.1.0"
lexer = { path = "../lexer" }
span = { path = "../span" }
utility = { path = "../utility" }
