[package]
name = "derivation-macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
heck = "0.4.0"
proc-macro2 = "1.0.36"
quote = "1.0.9"
syn = { version = "1.0.75", features = ["full"] }
