[package]
name = "derivation-macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
heck = "0.4.1"
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = { version = "1.0.109", features = ["full"] }
