name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest rustc nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Check if the Lushui compiler can compile
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Run unit tests (via the rust testing framework)
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run UI tests (via the golden UI testing framework)
      run: ./ui_tests/run

